// packages/vue/src/components/timeline/FrameworkRibbon.vue
<template>
	<div :class="[styles.ribbon, 'container']">
		<p :class="styles['ribbon-title']">Framework exposure</p>
		<div v-for="row in rows" :key="row.framework" :class="styles['ribbon-row']">
			<span :class="styles['ribbon-label']">{{ row.framework }}</span>
			<div :class="styles['ribbon-track']">
				<span
					v-for="(seg, i) in row.segments"
					:key="i"
					:class="styles['ribbon-seg']"
					:data-intensity="seg.intensity"
					:style="segStyle(seg)"
				/>
			</div>
		</div>
		<div :class="styles['ribbon-axis']">
			<span
				v-for="tick in ticks"
				:key="tick.year"
				:class="styles['ribbon-tick']"
				:style="{ left: `${tick.left}%` }"
			>
				{{ tick.year }}
			</span>
		</div>
		<div :class="styles['ribbon-legend']">
			<span v-for="item in intensityLegend" :key="item.intensity" :class="styles['legend-item']">
				<span :class="styles['legend-swatch']" :data-intensity="item.intensity" />
				{{ item.label }}
			</span>
		</div>
	</div>
</template>

<script setup lang="ts">
import type { RibbonSegment, TimelineData } from '@fg/shared';
import { axisTicks, ribbonRows } from '@fg/shared';
import styles from '@styles/components/timeline.module.css';

const props = defineProps<{ data: TimelineData }>();

const rows = ribbonRows(props.data);
const ticks = axisTicks(props.data);

const intensityLegend = [
	{ intensity: 'professional', label: 'Professional / daily' },
	{ intensity: 'occasional', label: 'Side-project' },
	{ intensity: 'brief', label: 'Brief' },
];

function segStyle(seg: RibbonSegment): Record<string, string> {
	return seg.intensity !== 'brief'
		? { left: `${seg.left}%`, width: `${seg.width}%` }
		: { left: `${seg.left}%` };
}
</script>

// packages/angular/src/components/timeline/framework-ribbon.component.ts
import { Component, computed, input } from '@angular/core';
import type { TimelineData } from '@fg/shared';
import { axisTicks, ribbonRows } from '@fg/shared';

@Component({
	selector: 'app-framework-ribbon',
	standalone: true,
	styleUrls: ['../../../../../styles/components/timeline.module.css'],
	styles: [':host { display: block; }'],
	template: `
		<div class="ribbon container">
			<p class="ribbon-title">Framework exposure</p>
			@for (row of rows(); track row.framework) {
				<div class="ribbon-row">
					<span class="ribbon-label">{{ row.framework }}</span>
					<div class="ribbon-track">
						@for (seg of row.segments; track $index) {
							<span
								class="ribbon-seg"
								[attr.data-intensity]="seg.intensity"
								[style.left.%]="seg.left"
								[style.width.%]="seg.intensity !== 'brief' ? seg.width : null"
							></span>
						}
					</div>
				</div>
			}
			<div class="ribbon-axis">
				@for (tick of ticks(); track tick.year) {
					<span class="ribbon-tick" [style.left.%]="tick.left">{{ tick.year }}</span>
				}
			</div>
			<div class="ribbon-legend">
				@for (item of intensityLegend; track item.intensity) {
					<span class="legend-item">
						<span class="legend-swatch" [attr.data-intensity]="item.intensity"></span>
						{{ item.label }}
					</span>
				}
			</div>
		</div>
	`,
})
export class FrameworkRibbonComponent {
	readonly data = input.required<TimelineData>();
	protected readonly rows = computed(() => ribbonRows(this.data()));
	protected readonly ticks = computed(() => axisTicks(this.data()));
	protected readonly intensityLegend = [
		{ intensity: 'professional', label: 'Professional / daily' },
		{ intensity: 'occasional', label: 'Side-project' },
		{ intensity: 'brief', label: 'Brief' },
	];
}
