// packages/react/src/pages/About.tsx
import { useContent } from '../content'

export function About() {
	const content = useContent('about')

	return (
		<section>
			<div className="container">
				<span className="section-label">About</span>
				<h2 className="section-title">{content?.title ?? 'Fortunato Geelhoed'}</h2>
				<p style={{ color: 'var(--text-secondary)' }}>
					{content?.body ??
						'About page content will be loaded from the content pipeline.'}
				</p>
			</div>
		</section>
	)
}

// packages/vue/src/pages/About.vue
<template>
	<section>
		<div class="container">
			<span class="section-label">About</span>
			<h2 class="section-title">{{ content?.title ?? 'Fortunato Geelhoed' }}</h2>
			<p style="color: var(--text-secondary)">{{ content?.body ?? 'About page content will be loaded from the content pipeline.' }}</p>
		</div>
	</section>
</template>

<script setup lang="ts">
import { useContent } from '../composables/useContent'

const { content } = useContent('about')
</script>
