// packages/angular/src/pages/blog.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-blog',
	standalone: true,
	template: `
		<section>
			<div class="container">
				<span class="section-label">Writing</span>
				<h1 class="section-title">Blog</h1>
				<p style="color: var(--jb-text-secondary); max-width: 40rem">
					Posts are on their way. The first pieces — on specialization, cognitive debt and
					building this site in three frameworks — are being prepared for publication here.
				</p>
			</div>
		</section>
	`,
})
export class BlogComponent {}

// packages/vue/src/pages/Blog.vue
<template>
	<section>
		<div class="container">
			<span class="section-label">Writing</span>
			<h1 class="section-title">Blog</h1>
			<p style="color: var(--jb-text-secondary); max-width: 40rem">
				Posts are on their way. The first pieces — on specialization, cognitive debt and building
				this site in three frameworks — are being prepared for publication here.
			</p>
		</div>
	</section>
</template>
