// packages/react/src/pages/Contact.tsx
import { ContactForm } from '../components/ContactForm';
import { useContent } from '../content';

export function Contact() {
	const content = useContent('contact');

	return (
		<section>
			<div className="container">
				<span className="section-label">Available Now</span>
				<h2 className="section-title">{content?.title ?? "Let's work together."}</h2>
				<p style={{ color: 'var(--jb-text-secondary)' }}>
					{content?.body ??
						'Get in touch for consulting, freelance projects, or collaboration.'}
				</p>

				<ContactForm />

				<p className="contact-meta">
					<jb-tech-tag>React</jb-tech-tag>
					<jb-tech-tag>TypeScript</jb-tech-tag>
					<jb-tech-tag>Vite</jb-tech-tag>
				</p>
			</div>
		</section>
	);
}

// packages/vue/src/pages/Contact.vue
<template>
	<section>
		<div class="container">
			<span class="section-label">Available Now</span>
			<h2 class="section-title">{{ content?.title ?? "Let's work together." }}</h2>
			<p style="color: var(--jb-text-secondary)">{{ content?.body ?? 'Get in touch for consulting, freelance projects, or collaboration.' }}</p>

			<ContactForm />

			<p class="contact-meta">
				<jb-tech-tag>Vue</jb-tech-tag>
				<jb-tech-tag>TypeScript</jb-tech-tag>
				<jb-tech-tag>Vite</jb-tech-tag>
			</p>
		</div>
	</section>
</template>

<script setup lang="ts">
import ContactForm from '../components/ContactForm.vue';
import { useContent } from '../composables/useContent';

const { content } = useContent('contact');
</script>
