// packages/react/src/pages/Home.tsx
import homeData from '@fg/content-data/home.json';
import type { HomeContent } from '@fg/shared';
import { Approach } from '../components/home/Approach';
import { CallToAction } from '../components/home/CallToAction';
import { FrameworkExposure } from '../components/home/FrameworkExposure';
import { Hero } from '../components/home/Hero';
import { LatestWriting } from '../components/home/LatestWriting';
import { ProofStrip } from '../components/home/ProofStrip';
import { Services } from '../components/home/Services';

const home = homeData as HomeContent;

export function Home() {
	return (
		<>
			<Hero hero={home.hero} />
			<Services services={home.services} copy={home.sections.services} />
			<Approach principles={home.principles} copy={home.sections.approach} />
			<FrameworkExposure copy={home.sections.frameworks} />
			<ProofStrip proof={home.proof} copy={home.sections.proof} />
			<LatestWriting writing={home.writing} copy={home.sections.writing} />
			<CallToAction cta={home.cta} />
		</>
	);
}

// packages/vue/src/pages/Home.vue
<template>
	<Hero :hero="home.hero" />
	<Services :services="home.services" :copy="home.sections.services" />
	<Approach :principles="home.principles" :copy="home.sections.approach" />
	<FrameworkExposure :copy="home.sections.frameworks" />
	<ProofStrip :proof="home.proof" :copy="home.sections.proof" />
	<LatestWriting :writing="home.writing" :copy="home.sections.writing" />
	<CallToAction :cta="home.cta" />
</template>

<script setup lang="ts">
import homeData from '@fg/content-data/home.json';
import type { HomeContent } from '@fg/shared';
import Approach from '../components/home/Approach.vue';
import CallToAction from '../components/home/CallToAction.vue';
import FrameworkExposure from '../components/home/FrameworkExposure.vue';
import Hero from '../components/home/Hero.vue';
import LatestWriting from '../components/home/LatestWriting.vue';
import ProofStrip from '../components/home/ProofStrip.vue';
import Services from '../components/home/Services.vue';

const home = homeData as HomeContent;
</script>
