// packages/vue/src/components/timeline/FrameworkRibbon.vue
<template>
	<div :class="[styles.ribbon, 'container']">
		<p :class="styles['ribbon-title']">Framework exposure</p>
		<div v-for="row in rows" :key="row.framework" :class="styles['ribbon-row']">
			<span :class="styles['ribbon-label']">{{ row.framework }}</span>
			<div :class="styles['ribbon-track']">
				<span
					v-for="(seg, i) in row.segments"
					:key="i"
					:class="styles['ribbon-seg']"
					:data-intensity="seg.intensity"
					:style="segStyle(seg)"
				/>
			</div>
		</div>
		<div :class="styles['ribbon-axis']">
			<span
				v-for="tick in ticks"
				:key="tick.year"
				:class="styles['ribbon-tick']"
				:style="{ left: `${tick.left}%` }"
			>
				{{ tick.year }}
			</span>
		</div>
		<div :class="styles['ribbon-legend']">
			<span v-for="item in intensityLegend" :key="item.intensity" :class="styles['legend-item']">
				<span :class="styles['legend-swatch']" :data-intensity="item.intensity" />
				{{ item.label }}
			</span>
		</div>
	</div>
</template>

<script setup lang="ts">
import type { RibbonSegment, TimelineData } from '@fg/shared';
import { axisTicks, ribbonRows } from '@fg/shared';
import styles from '@styles/components/timeline.module.css';

const props = defineProps<{ data: TimelineData }>();

const rows = ribbonRows(props.data);
const ticks = axisTicks(props.data);

const intensityLegend = [
	{ intensity: 'professional', label: 'Professional / daily' },
	{ intensity: 'occasional', label: 'Side-project' },
	{ intensity: 'brief', label: 'Brief' },
];

function segStyle(seg: RibbonSegment): Record<string, string> {
	return seg.intensity !== 'brief'
		? { left: `${seg.left}%`, width: `${seg.width}%` }
		: { left: `${seg.left}%` };
}
</script>

// packages/react/src/components/timeline/FrameworkRibbon.tsx
import type { TimelineData } from '@fg/shared';
import { axisTicks, ribbonRows } from '@fg/shared';
import styles from '@styles/components/timeline.module.css';

const INTENSITY_LEGEND: { intensity: string; label: string }[] = [
	{ intensity: 'professional', label: 'Professional / daily' },
	{ intensity: 'occasional', label: 'Side-project' },
	{ intensity: 'brief', label: 'Brief' },
];

export function FrameworkRibbon({ data }: { data: TimelineData }) {
	const rows = ribbonRows(data);
	const ticks = axisTicks(data);

	return (
		<div className={`${styles.ribbon} container`}>
			<p className={styles['ribbon-title']}>Framework exposure</p>
			{rows.map((row) => (
				<div key={row.framework} className={styles['ribbon-row']}>
					<span className={styles['ribbon-label']}>{row.framework}</span>
					<div className={styles['ribbon-track']}>
						{row.segments.map((seg, i) => (
							<span
								// biome-ignore lint/suspicious/noArrayIndexKey: segments are positional and stable
								key={i}
								className={styles['ribbon-seg']}
								data-intensity={seg.intensity}
								style={{
									left: `${seg.left}%`,
									...(seg.intensity !== 'brief'
										? { width: `${seg.width}%` }
										: {}),
								}}
							/>
						))}
					</div>
				</div>
			))}
			<div className={styles['ribbon-axis']}>
				{ticks.map((tick) => (
					<span
						key={tick.year}
						className={styles['ribbon-tick']}
						style={{ left: `${tick.left}%` }}
					>
						{tick.year}
					</span>
				))}
			</div>
			<div className={styles['ribbon-legend']}>
				{INTENSITY_LEGEND.map((item) => (
					<span key={item.intensity} className={styles['legend-item']}>
						<span className={styles['legend-swatch']} data-intensity={item.intensity} />
						{item.label}
					</span>
				))}
			</div>
		</div>
	);
}
