// packages/vue/src/components/timeline/TimelineEntry.vue
<template>
	<article :class="styles.entry" :data-type="entry.type" data-reveal>
		<div :class="styles.spine">
			<div :class="styles['spine-years']">{{ entry.years }}</div>
			<div :class="styles['spine-client']">{{ entry.client }}</div>
			<div :class="styles['spine-role']">{{ entry.role }}</div>
			<div :class="styles['spine-badges']">
				<span :class="styles['spine-type']" :data-type="entry.type">
					<svg v-if="entry.type === 'side-project'" :class="styles['type-icon']">
						<use href="#i-branch" />
					</svg>
					{{ typeLabel[entry.type] }}
				</span>
				<span v-if="entry.agency" :class="styles['spine-agency']">{{ agencyLabel }}</span>
			</div>
			<div v-if="entry.domains?.length" :class="styles['spine-domains']">
				<span v-for="d in entry.domains" :key="d" :class="styles.domain">{{ d }}</span>
			</div>
			<div v-for="h in highlights" :key="h" :class="styles['spine-highlight']">{{ h }}</div>
			<div v-if="entry.links?.length" :class="styles['spine-links']">
				<template v-for="l in entry.links" :key="l.href">
					<a
						v-if="isExternal(l.href)"
						:href="l.href"
						:class="[styles['spine-link'], styles['spine-link-external']]"
						target="_blank"
						rel="noopener noreferrer"
						:title="l.title"
						:aria-label="`${l.title ?? l.label} (opens in a new tab)`"
					>
						<jb-icon v-if="l.icon" :name="l.icon" />
						{{ l.label }}
					</a>
					<RouterLink v-else :to="l.href" :class="styles['spine-link']" :title="l.title">
						<jb-icon v-if="l.icon" :name="l.icon" />
						{{ l.label }}
					</RouterLink>
				</template>
			</div>
		</div>

		<template v-for="lane in lanes" :key="lane.key">
			<div
				v-if="entry.tech[lane.key]?.length"
				:class="[styles.lane, styles[lane.cls]]"
				:data-lane-label="laneLabels[lane.key]"
			>
				<span
					v-for="t in entry.tech[lane.key]"
					:key="t"
					:class="styles.pill"
					:style="{ '--brand': v(t).brand }"
				>
					<svg v-if="v(t).icon" :class="styles['pill-icon']"><use :href="`#i-${v(t).icon}`" /></svg>
					{{ t }}
				</span>
			</div>
		</template>
	</article>
</template>

<script setup lang="ts">
import type { Lane, TimelineEntry } from '@fg/shared';
import {
	AGENCY_LABEL,
	EMPLOYMENT_TYPE_LABELS,
	LANE_LABELS,
	isExternalHref,
	techVisual,
} from '@fg/shared';
import styles from '@styles/components/timeline.module.css';
import { computed } from 'vue';
import { RouterLink } from 'vue-router';

const props = defineProps<{ entry: TimelineEntry }>();

const highlights = computed<string[]>(() => {
	const h = props.entry.highlight;
	return h ? (Array.isArray(h) ? h : [h]) : [];
});

const laneLabels = LANE_LABELS;
const v = techVisual;
const lanes: { key: Lane; cls: string }[] = [
	{ key: 'frontend', cls: 'lane-fe' },
	{ key: 'backend', cls: 'lane-be' },
	{ key: 'cicd', cls: 'lane-ci' },
	{ key: 'ai', cls: 'lane-ai' },
];
const typeLabel = EMPLOYMENT_TYPE_LABELS;
const agencyLabel = AGENCY_LABEL;
const isExternal = isExternalHref;
</script>

// packages/react/src/components/timeline/TimelineEntry.tsx
import type { TimelineEntry as Entry, Lane } from '@fg/shared';
import {
	AGENCY_LABEL,
	EMPLOYMENT_TYPE_LABELS,
	LANE_LABELS,
	isExternalHref,
	techVisual,
} from '@fg/shared';
import styles from '@styles/components/timeline.module.css';
import type { CSSProperties } from 'react';
import { Link } from 'react-router';

const LANES: { key: Lane; cls: string }[] = [
	{ key: 'frontend', cls: 'lane-fe' },
	{ key: 'backend', cls: 'lane-be' },
	{ key: 'cicd', cls: 'lane-ci' },
	{ key: 'ai', cls: 'lane-ai' },
];

function highlights(entry: Entry): string[] {
	if (!entry.highlight) return [];
	return Array.isArray(entry.highlight) ? entry.highlight : [entry.highlight];
}

function Pill({ name }: { name: string }) {
	const { brand, icon } = techVisual(name);
	return (
		<span className={styles.pill} style={{ '--brand': brand } as CSSProperties}>
			{icon ? (
				<svg className={styles['pill-icon']} aria-hidden="true">
					<use href={`#i-${icon}`} />
				</svg>
			) : null}
			{name}
		</span>
	);
}

export function TimelineEntry({ entry }: { entry: Entry }) {
	return (
		<article className={styles.entry} data-type={entry.type} data-reveal>
			<div className={styles.spine}>
				<div className={styles['spine-years']}>{entry.years}</div>
				<div className={styles['spine-client']}>{entry.client}</div>
				<div className={styles['spine-role']}>{entry.role}</div>
				<div className={styles['spine-badges']}>
					<span className={styles['spine-type']} data-type={entry.type}>
						{entry.type === 'side-project' ? (
							<svg className={styles['type-icon']} aria-hidden="true">
								<use href="#i-branch" />
							</svg>
						) : null}
						{EMPLOYMENT_TYPE_LABELS[entry.type]}
					</span>
					{entry.agency ? (
						<span className={styles['spine-agency']}>{AGENCY_LABEL}</span>
					) : null}
				</div>
				{entry.domains?.length ? (
					<div className={styles['spine-domains']}>
						{entry.domains.map((d) => (
							<span key={d} className={styles.domain}>
								{d}
							</span>
						))}
					</div>
				) : null}
				{highlights(entry).map((h) => (
					<div key={h} className={styles['spine-highlight']}>
						{h}
					</div>
				))}
				{entry.links?.length ? (
					<div className={styles['spine-links']}>
						{entry.links.map((l) =>
							isExternalHref(l.href) ? (
								<a
									key={l.href}
									href={l.href}
									className={`${styles['spine-link']} ${styles['spine-link-external']}`}
									target="_blank"
									rel="noopener noreferrer"
									title={l.title}
									aria-label={`${l.title ?? l.label} (opens in a new tab)`}
								>
									{l.icon ? <jb-icon name={l.icon} /> : null}
									{l.label}
								</a>
							) : (
								<Link
									key={l.href}
									to={l.href}
									className={styles['spine-link']}
									title={l.title}
								>
									{l.icon ? <jb-icon name={l.icon} /> : null}
									{l.label}
								</Link>
							),
						)}
					</div>
				) : null}
			</div>

			{LANES.map(({ key, cls }) =>
				entry.tech[key]?.length ? (
					<div
						key={key}
						className={`${styles.lane} ${styles[cls]}`}
						data-lane-label={LANE_LABELS[key]}
					>
						{entry.tech[key]?.map((t) => (
							<Pill key={t} name={t} />
						))}
					</div>
				) : null,
			)}
		</article>
	);
}
