// packages/angular/src/components/home/framework-exposure.component.ts
import { Component } from '@angular/core';
import type { FrameworkExposureSpan } from '@fg/shared';
import { axisTicks, ribbonRows, spansBounds } from '@fg/shared';
import backend from '../../../../content/backend-frameworks.json';
import frontend from '../../../../content/frontend-frameworks.json';
import { FrameworkRibbonComponent } from '../timeline/framework-ribbon.component';

const frontendFrameworks = frontend as FrameworkExposureSpan[];
const backendFrameworks = backend as FrameworkExposureSpan[];
// Both ribbons share one axis so their years line up.
const bounds = spansBounds(frontendFrameworks, backendFrameworks);

@Component({
	selector: 'app-framework-exposure',
	standalone: true,
	imports: [FrameworkRibbonComponent],
	styleUrls: ['../../../../../styles/components/framework-ribbon.module.css'],
	template: `
		<section class="exposure">
			<div class="container exposure-body">
				<p class="section-label">Frameworks</p>
				<h2 class="section-title head">Frameworks come and go. The craft compounds.</h2>
				<p class="intro">
					Twenty-five years on the web means living through every frontend era and the
					backends beneath it, staying fluent while the stack reinvents itself.
				</p>
				<app-framework-ribbon title="Frontend Frameworks" [rows]="frontendRows" [ticks]="ticks" />
				<app-framework-ribbon title="Backend &amp; CMS" [rows]="backendRows" [ticks]="ticks" />
				<div class="ribbon-legend">
					@for (item of intensityLegend; track item.intensity) {
						<span class="legend-item">
							<span class="legend-swatch" [attr.data-intensity]="item.intensity"></span>
							{{ item.label }}
						</span>
					}
				</div>
			</div>
		</section>
	`,
})
export class FrameworkExposureComponent {
	protected readonly frontendRows = ribbonRows(frontendFrameworks, bounds);
	protected readonly backendRows = ribbonRows(backendFrameworks, bounds);
	protected readonly ticks = axisTicks(bounds);
	protected readonly intensityLegend = [
		{ intensity: 'professional', label: 'Professional / daily' },
		{ intensity: 'occasional', label: 'Occasional' },
		{ intensity: 'brief', label: 'Brief' },
	];
}

// packages/vue/src/components/home/FrameworkExposure.vue
<template>
	<section :class="styles.exposure">
		<div class="container" :class="styles['exposure-body']">
			<p class="section-label">Frameworks</p>
			<h2 :class="['section-title', styles.head]">
				Frameworks come and go. The craft compounds.
			</h2>
			<p :class="styles.intro">
				Twenty-five years on the web means living through every frontend era and the backends
				beneath it — and staying fluent while the stack reinvents itself.
			</p>
			<FrameworkRibbon title="Frontend Frameworks" :rows="frontendRows" :ticks="ticks" />
			<FrameworkRibbon title="Backend &amp; CMS" :rows="backendRows" :ticks="ticks" />
			<div :class="styles['ribbon-legend']">
				<span v-for="item in intensityLegend" :key="item.intensity" :class="styles['legend-item']">
					<span :class="styles['legend-swatch']" :data-intensity="item.intensity" />
					{{ item.label }}
				</span>
			</div>
		</div>
	</section>
</template>

<script setup lang="ts">
import type { FrameworkExposureSpan } from '@fg/shared';
import { axisTicks, ribbonRows, spansBounds } from '@fg/shared';
import styles from '@styles/components/framework-ribbon.module.css';
import backend from '../../../../content/backend-frameworks.json';
import frontend from '../../../../content/frontend-frameworks.json';
import FrameworkRibbon from '../timeline/FrameworkRibbon.vue';

const frontendFrameworks = frontend as FrameworkExposureSpan[];
const backendFrameworks = backend as FrameworkExposureSpan[];

// Both ribbons share one axis so their years line up.
const bounds = spansBounds(frontendFrameworks, backendFrameworks);
const frontendRows = ribbonRows(frontendFrameworks, bounds);
const backendRows = ribbonRows(backendFrameworks, bounds);
const ticks = axisTicks(bounds);

const intensityLegend = [
	{ intensity: 'professional', label: 'Professional / daily' },
	{ intensity: 'occasional', label: 'Occasional' },
	{ intensity: 'brief', label: 'Brief' },
];
</script>
