// packages/vue/src/components/BottomNav.vue
<template>
	<nav :class="styles['bottom-nav']" aria-label="Mobile">
		<RouterLink
			v-for="item in navItems"
			:key="item.path"
			:to="item.path"
			:class="styles['bottom-nav-item']"
		>
			<jb-icon :name="item.icon" />
			{{ item.label }}
		</RouterLink>
	</nav>
</template>

<script setup lang="ts">
import { NAV_ITEMS } from '@fg/shared';
import styles from '@styles/components/bottom-nav.module.css';
import { RouterLink } from 'vue-router';

const navItems = NAV_ITEMS;
</script>

// packages/react/src/components/BottomNav.tsx
import { NAV_ITEMS } from '@fg/shared';
import styles from '@styles/components/bottom-nav.module.css';
import { NavLink } from 'react-router';

// Mobile-first primary navigation (fixed bottom tab bar; hidden on wide viewports
// where the header's top-bar nav takes over). Driven by the shared NAV_ITEMS.
export function BottomNav() {
	return (
		<nav className={styles['bottom-nav']} aria-label="Mobile">
			{NAV_ITEMS.map((item) => (
				<NavLink
					key={item.path}
					to={item.path}
					end={item.path === '/'}
					className={styles['bottom-nav-item']}
				>
					<jb-icon name={item.icon} />
					{item.label}
				</NavLink>
			))}
		</nav>
	);
}
