// packages/angular/src/components/bottom-nav.component.ts
import { CUSTOM_ELEMENTS_SCHEMA, Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NAV_ITEMS } from '@fg/shared';

// Mobile-first primary navigation (fixed bottom tab bar; hidden on wide viewports).
// Driven by the shared NAV_ITEMS.
@Component({
	selector: 'app-bottom-nav',
	standalone: true,
	imports: [RouterLink, RouterLinkActive],
	// Allow the <jb-icon> custom element in this template.
	schemas: [CUSTOM_ELEMENTS_SCHEMA],
	styleUrl: '../../../../styles/components/bottom-nav.module.css',
	template: `
		<nav class="bottom-nav" aria-label="Mobile">
			@for (item of navItems; track item.path) {
				<a
					class="bottom-nav-item"
					[routerLink]="item.path"
					routerLinkActive
					[routerLinkActiveOptions]="{ exact: item.path === '/' }"
					ariaCurrentWhenActive="page"
				>
					<jb-icon [attr.name]="item.icon"></jb-icon>
					{{ item.label }}
				</a>
			}
		</nav>
	`,
})
export class BottomNavComponent {
	protected readonly navItems = NAV_ITEMS;
}

// packages/react/src/components/BottomNav.tsx
import { NAV_ITEMS } from '@fg/shared';
import styles from '@styles/components/bottom-nav.module.css';
import { NavLink } from 'react-router';

// Mobile-first primary navigation (fixed bottom tab bar; hidden on wide viewports
// where the header's top-bar nav takes over). Driven by the shared NAV_ITEMS.
export function BottomNav() {
	return (
		<nav className={styles['bottom-nav']} aria-label="Mobile">
			{NAV_ITEMS.map((item) => (
				<NavLink
					key={item.path}
					to={item.path}
					end={item.path === '/'}
					className={styles['bottom-nav-item']}
				>
					<jb-icon name={item.icon} />
					{item.label}
				</NavLink>
			))}
		</nav>
	);
}
