// packages/vue/src/components/ContactForm.vue
<template>
	<output v-if="sent" class="contact-success">Thanks, I'll be in touch shortly.</output>
	<form v-else novalidate class="contact-form" @submit.prevent="form.handleSubmit()">
		<form.Field
			name="name"
			:listeners="{ onChange: ({ fieldApi }) => fieldApi.setErrorMap({ onSubmit: undefined }) }"
		>
			<template #default="{ field }">
				<div class="contact-field">
					<jb-input
						name="name"
						label="Name"
						:value="field.state.value"
						:disabled="disabled"
						@input="field.handleChange(($event.target as HTMLInputElement).value)"
						@blur="field.handleBlur"
					/>
					<p v-if="field.state.meta.isTouched && field.state.meta.errors.length" class="field-error">
						{{ field.state.meta.errors[0]?.message }}
					</p>
				</div>
			</template>
		</form.Field>
		<form.Field
			name="email"
			:listeners="{ onChange: ({ fieldApi }) => fieldApi.setErrorMap({ onSubmit: undefined }) }"
		>
			<template #default="{ field }">
				<div class="contact-field">
					<jb-input
						name="email"
						type="email"
						label="Email"
						autocomplete="email"
						:value="field.state.value"
						:disabled="disabled"
						@input="field.handleChange(($event.target as HTMLInputElement).value)"
						@blur="field.handleBlur"
					/>
					<p v-if="field.state.meta.isTouched && field.state.meta.errors.length" class="field-error">
						{{ field.state.meta.errors[0]?.message }}
					</p>
				</div>
			</template>
		</form.Field>
		<form.Field
			name="message"
			:listeners="{ onChange: ({ fieldApi }) => fieldApi.setErrorMap({ onSubmit: undefined }) }"
		>
			<template #default="{ field }">
				<div class="contact-field">
					<jb-textarea
						name="message"
						label="Message"
						:value="field.state.value"
						:disabled="disabled"
						@input="field.handleChange(($event.target as HTMLTextAreaElement).value)"
						@blur="field.handleBlur"
					/>
					<p v-if="field.state.meta.isTouched && field.state.meta.errors.length" class="field-error">
						{{ field.state.meta.errors[0]?.message }}
					</p>
				</div>
			</template>
		</form.Field>
		<div class="contact-hp" aria-hidden="true">
			<input
				type="text"
				name="company"
				tabindex="-1"
				autocomplete="off"
				:value="company"
				@input="company = ($event.target as HTMLInputElement).value"
			/>
		</div>
		<p v-if="failed" class="contact-error" role="alert">
			Something went wrong sending your message. Please try again.
		</p>
		<p class="contact-privacy">
			Your name, email, and message are emailed to me so I can reply — they are not stored on
			this site.
		</p>
		<button type="submit" class="btn" :disabled="disabled">Send</button>
	</form>
</template>

<script setup lang="ts">
// Contact form composite built with TanStack Form. A single Zod schema — shared with the React
// and Angular forms and with the server that receives the submission — drives validation: TanStack
// consumes it directly through the Standard Schema interface, so the rules live in one place.
// Binding stays on :value + @input (Vue's compiler disallows v-model on custom elements).
import { type ContactFormData, contactSchema } from '@fg/shared/validation/contact';
import { useForm } from '@tanstack/vue-form';
import { ref } from 'vue';

// Disables every control — used while a submission is in flight and by the showcase.
withDefaults(defineProps<{ disabled?: boolean }>(), { disabled: false });

const sent = ref(false);
// True when a valid submission could not be delivered (a 502, or the request never reached the
// server). Surfaces a general "try again" message rather than a false success.
const failed = ref(false);
// Honeypot: a hidden field no human fills. Sent with the payload; the server silently drops any
// submission that arrives with it set. Kept out of the shared schema so it stays a private trap.
const company = ref('');

const form = useForm({
	defaultValues: { name: '', email: '', message: '' } as ContactFormData,
	validators: {
		onChange: contactSchema,
		// The submission itself. The server re-validates with the same schema (authoritative);
		// returning field errors here surfaces them on the matching fields through TanStack's own
		// error state. Each field's listener clears its own server error on edit (matching React and
		// Angular), so there is no parallel server-error store.
		onSubmitAsync: async ({ value }) => {
			failed.value = false;
			let res: Response;
			try {
				res = await fetch('/api/contact', {
					method: 'POST',
					headers: { 'content-type': 'application/json' },
					body: JSON.stringify({ ...value, company: company.value }),
				});
			} catch {
				// Never reached the server — fail the submit so the success view does not show.
				failed.value = true;
				return 'send-failed';
			}
			if (res.ok) return undefined;
			const body = (await res.json().catch(() => null)) as {
				errors?: Partial<Record<keyof ContactFormData, string[]>>;
			} | null;
			const fields: Partial<Record<keyof ContactFormData, { message: string }>> = {};
			for (const field of ['name', 'email', 'message'] as const) {
				const message = body?.errors?.[field]?.[0];
				if (message) fields[field] = { message };
			}
			// A 502 (valid but undelivered) carries no field errors — surface the general message
			// and keep the submit failed so onSubmit (success) never runs.
			if (Object.keys(fields).length === 0) {
				failed.value = true;
				return 'send-failed';
			}
			return { fields };
		},
	},
	onSubmit: () => {
		sent.value = true;
	},
});
</script>

// packages/react/src/components/ContactForm.tsx
import { type ContactFormData, contactSchema } from '@fg/shared/validation/contact';
import { zodResolver } from '@hookform/resolvers/zod';
import { useState } from 'react';
import { Controller, useForm } from 'react-hook-form';

interface ContactFormProps {
	// Disables every control — used while a submission is in flight and by the showcase.
	disabled?: boolean;
}

const FIELDS = ['name', 'email', 'message'] as const;

// Contact form composite built with react-hook-form. A single Zod schema — shared with the
// Vue and Angular forms and with the server that receives the submission — drives validation
// through zodResolver, so the rules live in one place. <Controller> bridges each <jb-*> web
// component (controlled via its `value` property and bubbling native `input` event) to a field.
export function ContactForm({ disabled = false }: ContactFormProps) {
	const [sent, setSent] = useState(false);
	// True when a valid submission could not be delivered (a 502, or the request never reached the
	// server). Surfaces a general "try again" message rather than a false success.
	const [failed, setFailed] = useState(false);
	// Honeypot: a hidden field no human fills. Sent with the payload; the server silently drops any
	// submission that arrives with it set. Kept out of the shared schema so it stays a private trap.
	const [company, setCompany] = useState('');

	const {
		control,
		handleSubmit,
		setError,
		formState: { errors },
	} = useForm<ContactFormData>({
		resolver: zodResolver(contactSchema),
		defaultValues: { name: '', email: '', message: '' },
		mode: 'onTouched',
	});

	// The server re-validates with the same schema and is authoritative. Map any 4xx field errors
	// back onto react-hook-form's own error state via setError; they clear automatically when the
	// field re-validates on the next edit (reValidateMode defaults to 'onChange').
	const onSubmit = handleSubmit(async (data) => {
		setFailed(false);
		let res: Response;
		try {
			res = await fetch('/api/contact', {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify({ ...data, company }),
			});
		} catch {
			// Never reached the server (offline, aborted) — show the general failure.
			setFailed(true);
			return;
		}
		if (res.ok) {
			setSent(true);
			return;
		}
		// A 422 carries field errors to map back onto the inputs; a 502 (valid but undelivered) or
		// any other failure has none, so it surfaces as a general "try again" message.
		const body = (await res.json().catch(() => null)) as {
			errors?: Partial<Record<keyof ContactFormData, string[]>>;
		} | null;
		let hadFieldError = false;
		for (const field of FIELDS) {
			const message = body?.errors?.[field]?.[0];
			if (message) {
				setError(field, { type: 'server', message });
				hadFieldError = true;
			}
		}
		if (!hadFieldError) setFailed(true);
	});

	if (sent) {
		return <output className="contact-success">Thanks, I'll be in touch shortly.</output>;
	}

	return (
		<form onSubmit={onSubmit} noValidate className="contact-form">
			<Controller
				control={control}
				name="name"
				render={({ field }) => (
					<div className="contact-field">
						<jb-input
							name="name"
							label="Name"
							value={field.value}
							disabled={disabled}
							onInput={(e) => field.onChange((e.target as HTMLInputElement).value)}
							onBlur={field.onBlur}
						/>
						{errors.name?.message && (
							<p className="field-error">{errors.name.message}</p>
						)}
					</div>
				)}
			/>
			<Controller
				control={control}
				name="email"
				render={({ field }) => (
					<div className="contact-field">
						<jb-input
							name="email"
							type="email"
							label="Email"
							autocomplete="email"
							value={field.value}
							disabled={disabled}
							onInput={(e) => field.onChange((e.target as HTMLInputElement).value)}
							onBlur={field.onBlur}
						/>
						{errors.email?.message && (
							<p className="field-error">{errors.email.message}</p>
						)}
					</div>
				)}
			/>
			<Controller
				control={control}
				name="message"
				render={({ field }) => (
					<div className="contact-field">
						<jb-textarea
							name="message"
							label="Message"
							value={field.value}
							disabled={disabled}
							onInput={(e) => field.onChange((e.target as HTMLTextAreaElement).value)}
							onBlur={field.onBlur}
						/>
						{errors.message?.message && (
							<p className="field-error">{errors.message.message}</p>
						)}
					</div>
				)}
			/>
			<div className="contact-hp" aria-hidden="true">
				<input
					type="text"
					name="company"
					tabIndex={-1}
					autoComplete="off"
					value={company}
					onChange={(e) => setCompany(e.target.value)}
				/>
			</div>
			{failed && (
				<p className="contact-error" role="alert">
					Something went wrong sending your message. Please try again.
				</p>
			)}
			<p className="contact-privacy">
				Your name, email, and message are emailed to me so I can reply — they are not stored
				on this site.
			</p>
			<button type="submit" className="btn" disabled={disabled}>
				Send
			</button>
		</form>
	);
}
