// packages/angular/src/components/home/services.component.ts
import { Component, input } from '@angular/core';
import type { ServiceOffering } from '@fg/shared';

@Component({
	selector: 'app-services',
	standalone: true,
	styleUrl: '../../../../../styles/components/home.module.css',
	template: `
		<section>
			<div class="container">
				<p class="section-label">What I do</p>
				<h2 class="section-title">Services</h2>
				<div class="services-grid">
					@for (service of services(); track service.title) {
						<article class="card" data-reveal>
							<h3 class="service-title">{{ service.title }}</h3>
							<p class="service-desc">{{ service.description }}</p>
						</article>
					}
				</div>
			</div>
		</section>
	`,
})
export class ServicesComponent {
	readonly services = input.required<ServiceOffering[]>();
}

// packages/react/src/components/home/Services.tsx
import type { ServiceOffering } from '@fg/shared';
import styles from '@styles/components/home.module.css';

export function Services({ services }: { services: ServiceOffering[] }) {
	return (
		<section>
			<div className="container">
				<p className="section-label">What I do</p>
				<h2 className="section-title">Services</h2>
				<div className={styles['services-grid']}>
					{services.map((service) => (
						<article key={service.title} className="card" data-reveal>
							<h3 className={styles['service-title']}>{service.title}</h3>
							<p className={styles['service-desc']}>{service.description}</p>
						</article>
					))}
				</div>
			</div>
		</section>
	);
}
