// packages/angular/src/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { FooterComponent } from './components/footer.component';
import { HeaderComponent } from './components/header.component';

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [RouterOutlet, HeaderComponent, FooterComponent],
	template: '<app-header /><main><router-outlet /></main><app-footer />',
})
export class AppComponent {}

// packages/vue/src/App.vue
<template>
	<Header />
	<main>
		<RouterView />
	</main>
	<Footer />
	<BottomNav />
</template>

<script setup lang="ts">
import { RouterView } from 'vue-router';
import BottomNav from './components/BottomNav.vue';
import Footer from './components/Footer.vue';
import Header from './components/Header.vue';
</script>
