// packages/react/src/components/Footer.tsx
import styles from '@styles/components/footer.module.css';

export function Footer() {
	return (
		<footer className={styles.footer}>
			<div className={`${styles['footer-inner']} container`}>
				<span className={styles['footer-brand']}>
					FORTUNATO<span className={styles['footer-dot']}>.</span>GEELHOED
				</span>
				<nav className={styles['footer-links']} aria-label="Social and external links">
					<a
						href="https://www.linkedin.com/in/fortunatogeelhoed/"
						target="_blank"
						rel="noopener noreferrer"
					>
						<jb-icon name="linkedin" />
						LinkedIn
					</a>
					<a
						href="https://github.com/fortunato"
						target="_blank"
						rel="noopener noreferrer"
					>
						<jb-icon name="github" />
						GitHub
					</a>
				</nav>
				<p className={styles['footer-legal']}>
					© {new Date().getFullYear()} JiggyBit S.L. — built in React, Vue and Angular on
					one backend.
				</p>
			</div>
		</footer>
	);
}

// packages/vue/src/components/Footer.vue
<template>
	<footer :class="styles.footer">
		<div :class="[styles['footer-inner'], 'container']">
			<span :class="styles['footer-brand']">
				FORTUNATO<span :class="styles['footer-dot']">.</span>GEELHOED
			</span>
			<nav :class="styles['footer-links']" aria-label="Social and external links">
				<a
					href="https://www.linkedin.com/in/fortunatogeelhoed/"
					target="_blank"
					rel="noopener noreferrer"
				>
					<jb-icon name="linkedin" />
					LinkedIn
				</a>
				<a href="https://github.com/fortunato" target="_blank" rel="noopener noreferrer">
					<jb-icon name="github" />
					GitHub
				</a>
			</nav>
			<p :class="styles['footer-legal']">
				© {{ year }} JiggyBit S.L., built in React, Vue and Angular on one backend.
			</p>
		</div>
	</footer>
</template>

<script setup lang="ts">
import styles from '@styles/components/footer.module.css';

const year = new Date().getFullYear();
</script>
