// packages/react/src/pages/About.tsx
import { useContent } from '../content'

export function About() {
	const content = useContent('about')

	return (
		<section>
			<div className="container">
				<span className="section-label">About</span>
				<h2 className="section-title">{content?.title ?? 'Fortunato Geelhoed'}</h2>
				<p style={{ color: 'var(--text-secondary)' }}>
					{content?.body ??
						'About page content will be loaded from the content pipeline.'}
				</p>
			</div>
		</section>
	)
}

// packages/angular/src/pages/about.component.ts
import { Component } from '@angular/core'

@Component({
	selector: 'app-about',
	standalone: true,
	template: `
		<section>
			<div class="container">
				<span class="section-label">About</span>
				<h2 class="section-title">Fortunato Geelhoed</h2>
				<p style="color: var(--text-secondary)">About page content will be loaded from the content pipeline.</p>
			</div>
		</section>
	`,
})
export class AboutComponent {}
