// packages/react/src/pages/Work.tsx
export function Work() {
	return (
		<section>
			<div className="container">
				<span className="section-label">Selected Work</span>
				<h2 className="section-title">Case Studies</h2>
				<p style={{ color: 'var(--text-secondary)' }}>
					Work page content will be loaded from the content pipeline.
				</p>
			</div>
		</section>
	)
}

// packages/angular/src/pages/work.component.ts
import { Component } from '@angular/core'

@Component({
	selector: 'app-work',
	standalone: true,
	template: `
		<section>
			<div class="container">
				<span class="section-label">Selected Work</span>
				<h2 class="section-title">Case Studies</h2>
				<p style="color: var(--text-secondary)">Work page content will be loaded from the content pipeline.</p>
			</div>
		</section>
	`,
})
export class WorkComponent {}
