// packages/vue/src/components/home/ProofStrip.vue
<template>
	<section data-band :aria-label="copy.label">
		<div class="container" :class="styles['proof-body']">
			<p class="section-label">{{ copy.label }}</p>
			<dl :class="styles['proof-grid']">
				<div v-for="point in proof" :key="point.label" :class="styles['proof-item']" data-reveal>
					<dt :class="styles['proof-label']">{{ point.label }}</dt>
					<dd :class="styles['proof-metric']">{{ point.metric }}</dd>
				</div>
			</dl>
		</div>
	</section>
</template>

<script setup lang="ts">
import type { HomeContent, ProofPoint } from '@fg/shared';
import styles from '@styles/components/proof.module.css';

defineProps<{ proof: ProofPoint[]; copy: HomeContent['sections']['proof'] }>();
</script>

// packages/angular/src/components/home/proof-strip.component.ts
import { Component, input } from '@angular/core';
import type { HomeContent, ProofPoint } from '@fg/shared';

@Component({
	selector: 'app-proof-strip',
	standalone: true,
	styleUrl: '../../../../../styles/components/proof.module.css',
	template: `
		<section data-band [attr.aria-label]="copy().label">
			<div class="container proof-body">
				<p class="section-label">{{ copy().label }}</p>
				<dl class="proof-grid">
					@for (point of proof(); track point.label) {
						<div class="proof-item" data-reveal>
							<dt class="proof-label">{{ point.label }}</dt>
							<dd class="proof-metric">{{ point.metric }}</dd>
						</div>
					}
				</dl>
			</div>
		</section>
	`,
})
export class ProofStripComponent {
	readonly proof = input.required<ProofPoint[]>();
	readonly copy = input.required<HomeContent['sections']['proof']>();
}
